### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc26xx

### Add to the source dirs
CONTIKI_TARGET_DIRS += momote/cc2650

### Include the common momote makefile
include $(PLATFORM_ROOT_DIR)/momote/Makefile.momote
